server:
  port: 8087
  servlet:
    context-path: /catalog-service

spring:
  application:
    name: catalog-service
  datasource:
    url: jdbc:mysql://localhost:3306/catalog_service
    username: root
    password: Credable@01
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      default-zone: http://localhost:8761/eureka


